// =============================================================
// Curated recipe database + pricing/aisle lookup tables for the
// Meal Planner. No AI/external API — this is the full data set
// the deterministic scoring engine in meals-app.js selects from.
// =============================================================
window.MEALS_RECIPES = [
  { id:'r01', title:'Chicken Burrito Bowl', emoji:'🌯', tags:['mexican','healthy','high_protein'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:25, cal:620, protein:48, carbs:58, fat:18, cost:4.80,
    ingredients:[['chicken breast',200,'g'],['rice',150,'g'],['black beans',1,'can'],['sweetcorn',1,'can'],['pepper',1,'pcs'],['lime',1,'pcs']],
    steps:['Season and pan-fry the chicken breast until cooked through, then slice.','Cook the rice according to packet instructions.','Warm the beans and sweetcorn in a pan.','Build the bowl: rice, chicken, beans, corn, sliced pepper, a squeeze of lime.'] },
  { id:'r02', title:'Air Fryer Salmon', emoji:'🐟', tags:['healthy','high_protein','quick'], appliances:['air_fryer'], diet:{vegan:false,vegetarian:false,pescatarian:true,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:18, cal:540, protein:42, carbs:8, fat:34, cost:5.50,
    ingredients:[['salmon fillet',200,'g'],['asparagus',150,'g'],['lemon',1,'pcs'],['olive oil',1,'tbsp']],
    steps:['Rub salmon with olive oil, salt and pepper.','Air fry salmon at 200°C for 10-12 minutes.','Air fry asparagus for 6-8 minutes.','Serve with a lemon wedge.'] },
  { id:'r03', title:'Turkey Pasta', emoji:'🍝', tags:['pasta','comfort','family'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:25, cal:580, protein:38, carbs:62, fat:16, cost:3.60,
    ingredients:[['turkey mince',250,'g'],['pasta',200,'g'],['tomato',400,'g'],['onion',1,'pcs'],['garlic',2,'pcs'],['basil',1,'bunch']],
    steps:['Brown the turkey mince with diced onion and garlic.','Add chopped tomato and simmer 12 minutes.','Cook pasta according to packet instructions.','Combine and finish with torn basil.'] },
  { id:'r04', title:'Thai Green Curry', emoji:'🍛', tags:['asian','comfort'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:30, cal:650, protein:34, carbs:52, fat:30, cost:4.40,
    ingredients:[['chicken thigh',250,'g'],['coconut milk',1,'can'],['green curry paste',2,'tbsp'],['green beans',150,'g'],['rice',150,'g']],
    steps:['Fry curry paste for 1 minute, then add diced chicken.','Pour in coconut milk and simmer 15 minutes.','Add green beans for the final 5 minutes.','Serve over steamed rice.'] },
  { id:'r05', title:'Chicken Wraps', emoji:'🌮', tags:['mexican','quick','fakeaway'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:15, cal:520, protein:36, carbs:46, fat:20, cost:3.90,
    ingredients:[['cooked chicken',200,'g'],['tortilla',2,'pcs'],['lettuce',1,'bunch'],['cheese',60,'g'],['salsa',2,'tbsp']],
    steps:['Warm the cooked chicken through (great use for roast chicken leftovers).','Warm tortillas.','Fill with chicken, lettuce, cheese and salsa, then roll.'] },
  { id:'r06', title:'Steak Bowl', emoji:'🥩', tags:['high_protein','healthy'], appliances:['bbq','hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:false,kosher:false}, cookTime:20, cal:680, protein:46, carbs:50, fat:28, cost:6.50,
    ingredients:[['steak',200,'g'],['rice',150,'g'],['pepper',1,'pcs'],['onion',1,'pcs'],['chimichurri',2,'tbsp']],
    steps:['Sear the steak 3-4 minutes each side, rest, then slice.','Char pepper and onion on the grill or in a hot pan.','Serve over rice with chimichurri spooned over.'] },
  { id:'r07', title:'Roast Chicken', emoji:'🍗', tags:['family','comfort'], appliances:['oven'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:60, cal:700, protein:52, carbs:44, fat:32, cost:5.20,
    ingredients:[['whole chicken',1,'pcs'],['potato',500,'g'],['carrot',300,'g'],['onion',1,'pcs'],['thyme',1,'bunch']],
    steps:['Season chicken and roast at 190°C for ~1hr 20 (20 min/500g).','Roast potatoes and carrots alongside for the last 45 minutes.','Rest chicken 10 minutes before carving.',"Save leftover chicken for Tuesday's wraps."] },
  { id:'r08', title:'Chicken Fried Rice', emoji:'🍚', tags:['asian','quick','one_pot'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:20, cal:560, protein:32, carbs:60, fat:18, cost:2.80,
    ingredients:[['cooked chicken',200,'g'],['rice',200,'g'],['egg',2,'pcs'],['peas',100,'g'],['soy sauce',2,'tbsp'],['spring onion',1,'bunch']],
    steps:['Scramble the egg in a hot wok, set aside.','Fry rice, chicken and peas together for 4-5 minutes.','Add soy sauce and egg back in, toss.','Top with spring onion.'] },
  { id:'r09', title:'Veggie Chilli', emoji:'🌶️', tags:['vegan','budget','one_pot'], appliances:['hob'], diet:{vegan:true,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:30, cal:480, protein:20, carbs:70, fat:10, cost:2.20,
    ingredients:[['kidney beans',1,'can'],['tomato',400,'g'],['pepper',1,'pcs'],['onion',1,'pcs'],['chilli',1,'pcs'],['rice',150,'g']],
    steps:['Fry onion, pepper and chilli for 5 minutes.','Add beans and tomato, simmer 15 minutes.','Cook rice separately.','Serve chilli over rice.'] },
  { id:'r10', title:'Margherita Pizza', emoji:'🍕', tags:['italian','family','comfort'], appliances:['oven'], diet:{vegan:false,vegetarian:true,pescatarian:true,glutenFree:false,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:25, cal:620, protein:26, carbs:70, fat:24, cost:3.10,
    ingredients:[['pizza dough',1,'pcs'],['tomato',200,'g'],['mozzarella',150,'g'],['basil',1,'bunch']],
    steps:['Roll out dough and spread with crushed tomato.','Top with torn mozzarella.','Bake at 220°C for 12-15 minutes.','Finish with fresh basil.'] },
  { id:'r11', title:'Beef Stir Fry', emoji:'🥘', tags:['asian','quick','high_protein'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:true,nutFree:true,halal:false,kosher:false}, cookTime:18, cal:560, protein:40, carbs:46, fat:20, cost:4.90,
    ingredients:[['beef strips',200,'g'],['broccoli',150,'g'],['pepper',1,'pcs'],['soy sauce',2,'tbsp'],['rice',150,'g']],
    steps:['Stir-fry beef strips on high heat 2-3 minutes, remove.','Stir-fry broccoli and pepper 4 minutes.','Return beef, add soy sauce, toss together.','Serve over rice.'] },
  { id:'r12', title:'Slow Cooker Beef Stew', emoji:'🍲', tags:['comfort','family','budget'], appliances:['slow_cooker'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:false,kosher:false}, cookTime:240, cal:580, protein:38, carbs:44, fat:22, cost:4.10,
    ingredients:[['beef chunks',300,'g'],['potato',300,'g'],['carrot',200,'g'],['onion',1,'pcs'],['stock',500,'ml']],
    steps:['Brown beef chunks, then add to slow cooker.','Add potato, carrot, onion and stock.','Cook on low for 6-7 hours.','Season to taste before serving.'] },
  { id:'r13', title:'Pressure Cooker Chickpea Curry', emoji:'🍛', tags:['vegan','healthy','budget'], appliances:['pressure_cooker'], diet:{vegan:true,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:25, cal:500, protein:22, carbs:66, fat:14, cost:1.90,
    ingredients:[['chickpeas',1,'can'],['tomato',400,'g'],['onion',1,'pcs'],['spinach',100,'g'],['rice',150,'g']],
    steps:['Sauté onion in the pressure cooker.','Add chickpeas and tomato, seal and cook on high pressure 8 minutes.','Stir in spinach to wilt.','Serve with rice.'] },
  { id:'r14', title:'Halloumi Salad Bowl', emoji:'🥗', tags:['vegetarian','healthy','quick'], appliances:['hob'], diet:{vegan:false,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:15, cal:480, protein:22, carbs:24, fat:32, cost:3.60,
    ingredients:[['halloumi',150,'g'],['mixed leaves',100,'g'],['tomato',150,'g'],['cucumber',1,'pcs'],['olive oil',1,'tbsp']],
    steps:['Pan-fry sliced halloumi until golden on both sides.','Toss leaves, tomato and cucumber with olive oil.','Top salad with warm halloumi.'] },
  { id:'r15', title:'Fish Tacos', emoji:'🐠', tags:['pescatarian','mexican','quick'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:true,glutenFree:false,dairyFree:true,nutFree:true,halal:true,kosher:false}, cookTime:20, cal:520, protein:34, carbs:48, fat:18, cost:4.70,
    ingredients:[['white fish',250,'g'],['tortilla',2,'pcs'],['cabbage',100,'g'],['lime',1,'pcs'],['salsa',2,'tbsp']],
    steps:['Season and pan-fry fish until just cooked, flake.','Warm tortillas.','Fill with fish, shredded cabbage and salsa.','Finish with a squeeze of lime.'] },
  { id:'r16', title:'Spaghetti Bolognese', emoji:'🍝', tags:['pasta','italian','family','comfort'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:true,nutFree:true,halal:false,kosher:false}, cookTime:35, cal:610, protein:36, carbs:64, fat:20, cost:3.30,
    ingredients:[['beef mince',250,'g'],['spaghetti',200,'g'],['tomato',400,'g'],['onion',1,'pcs'],['garlic',2,'pcs']],
    steps:['Brown mince with onion and garlic.','Add tomato, simmer 20 minutes.','Cook spaghetti.','Combine and serve.'] },
  { id:'r17', title:'Air Fryer Chicken Thighs', emoji:'🍗', tags:['high_protein','quick','healthy'], appliances:['air_fryer'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:22, cal:560, protein:44, carbs:34, fat:24, cost:4.20,
    ingredients:[['chicken thigh',250,'g'],['broccoli',150,'g'],['sweet potato',250,'g']],
    steps:['Air fry chicken thighs at 190°C for 18-20 minutes.','Air fry sweet potato wedges and broccoli alongside.','Season everything and serve.'] },
  { id:'r18', title:'Lentil Dahl', emoji:'🍲', tags:['vegan','budget','healthy'], appliances:['hob'], diet:{vegan:true,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:30, cal:460, protein:20, carbs:70, fat:10, cost:1.60,
    ingredients:[['lentils',200,'g'],['onion',1,'pcs'],['garlic',2,'pcs'],['tomato',200,'g'],['rice',150,'g']],
    steps:['Sauté onion and garlic, add lentils and tomato.','Add water, simmer 20 minutes until soft.','Cook rice.','Serve dahl over rice.'] },
  { id:'r19', title:'BBQ Pulled Pork', emoji:'🍖', tags:['bbq','comfort','family'], appliances:['slow_cooker'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:true,nutFree:true,halal:false,kosher:false}, cookTime:360, cal:650, protein:40, carbs:50, fat:28, cost:4.80,
    ingredients:[['pork shoulder',300,'g'],['bbq sauce',1,'can'],['bun',2,'pcs'],['coleslaw',1,'pcs']],
    steps:['Slow cook pork shoulder with bbq sauce on low for 8 hours.','Shred the pork.','Pile into buns with coleslaw.'] },
  { id:'r20', title:'Prawn Stir Fry', emoji:'🍤', tags:['pescatarian','asian','quick'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:true,glutenFree:false,dairyFree:true,nutFree:true,halal:true,kosher:false}, cookTime:16, cal:540, protein:32, carbs:54, fat:18, cost:5.30,
    ingredients:[['prawns',200,'g'],['noodles',200,'g'],['pepper',1,'pcs'],['soy sauce',2,'tbsp'],['ginger',10,'g']],
    steps:['Stir-fry prawns 2-3 minutes until pink, remove.','Stir-fry pepper and ginger.','Add noodles and soy sauce, toss with prawns.'] },
  { id:'r21', title:'Mushroom Risotto', emoji:'🍚', tags:['vegetarian','comfort','italian'], appliances:['hob'], diet:{vegan:false,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:30, cal:560, protein:16, carbs:70, fat:20, cost:3.20,
    ingredients:[['arborio rice',200,'g'],['mushroom',200,'g'],['onion',1,'pcs'],['parmesan',40,'g'],['stock',700,'ml']],
    steps:['Sauté onion and mushroom.','Add rice, stir 1 minute, then add stock gradually, stirring.','Cook 18-20 minutes until creamy.','Finish with parmesan.'] },
  { id:'r22', title:'Turkey Chilli', emoji:'🌶️', tags:['high_protein','budget','one_pot'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:28, cal:500, protein:40, carbs:40, fat:14, cost:3.50,
    ingredients:[['turkey mince',250,'g'],['kidney beans',1,'can'],['tomato',400,'g'],['pepper',1,'pcs']],
    steps:['Brown turkey mince.','Add beans, tomato and pepper, simmer 18 minutes.','Season and serve.'] },
  { id:'r23', title:'Greek Salad with Chicken', emoji:'🥙', tags:['healthy','quick'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:15, cal:480, protein:38, carbs:16, fat:28, cost:4.10,
    ingredients:[['chicken breast',200,'g'],['cucumber',1,'pcs'],['tomato',150,'g'],['feta',60,'g'],['olives',40,'g']],
    steps:['Pan-fry and slice the chicken.','Chop cucumber and tomato.','Toss with feta and olives, top with chicken.'] },
  { id:'r24', title:'Microwave Jacket Potato & Beans', emoji:'🥔', tags:['quick','budget','vegetarian'], appliances:['microwave'], diet:{vegan:false,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:12, cal:420, protein:18, carbs:66, fat:10, cost:1.40,
    ingredients:[['potato',1,'pcs'],['baked beans',1,'can'],['cheese',40,'g']],
    steps:['Microwave the potato 8-10 minutes, turning halfway.','Heat the beans.','Split potato, top with beans and cheese.'] },
  { id:'r25', title:'Chicken Tikka Masala', emoji:'🍛', tags:['asian','comfort','family'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:35, cal:640, protein:40, carbs:50, fat:28, cost:4.30,
    ingredients:[['chicken breast',250,'g'],['tomato',300,'g'],['cream',100,'ml'],['curry paste',2,'tbsp'],['rice',150,'g']],
    steps:['Fry curry paste, add diced chicken, brown.','Add tomato, simmer 15 minutes.','Stir in cream for 5 minutes.','Serve with rice.'] },
  { id:'r26', title:'One Pot Sausage Pasta', emoji:'🌭', tags:['one_pot','comfort','family','quick'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:true,nutFree:true,halal:false,kosher:false}, cookTime:25, cal:610, protein:28, carbs:64, fat:24, cost:3.40,
    ingredients:[['sausage',4,'pcs'],['pasta',200,'g'],['tomato',400,'g'],['pepper',1,'pcs']],
    steps:['Brown sliced sausage with pepper.','Add tomato, pasta and enough water to cover, simmer 15 minutes covered.','Stir occasionally until pasta is cooked.'] },
  { id:'r27', title:'Beef Burrito Bowl', emoji:'🌯', tags:['mexican','high_protein'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:false,nutFree:true,halal:false,kosher:false}, cookTime:22, cal:640, protein:42, carbs:56, fat:24, cost:4.60,
    ingredients:[['beef mince',250,'g'],['rice',150,'g'],['black beans',1,'can'],['sweetcorn',1,'can'],['cheese',50,'g']],
    steps:['Brown the beef mince with taco seasoning.','Cook rice.','Warm beans and corn.','Assemble bowl and top with cheese.'] },
  { id:'r28', title:'Vegan Buddha Bowl', emoji:'🥗', tags:['vegan','healthy','quick'], appliances:['hob'], diet:{vegan:true,vegetarian:true,pescatarian:true,glutenFree:true,dairyFree:true,nutFree:false,halal:true,kosher:true}, cookTime:18, cal:500, protein:24, carbs:52, fat:20, cost:3.80,
    ingredients:[['tofu',200,'g'],['quinoa',150,'g'],['broccoli',150,'g'],['carrot',100,'g'],['tahini',1,'tbsp']],
    steps:['Pan-fry cubed tofu until golden.','Cook quinoa.','Steam broccoli and shred carrot.','Assemble bowl, drizzle with tahini.'] },
  { id:'r29', title:'Fish and Chips', emoji:'🍟', tags:['pescatarian','comfort','fakeaway'], appliances:['oven'], diet:{vegan:false,vegetarian:false,pescatarian:true,glutenFree:false,dairyFree:true,nutFree:true,halal:true,kosher:false}, cookTime:35, cal:680, protein:36, carbs:70, fat:28, cost:4.50,
    ingredients:[['white fish',250,'g'],['potato',400,'g'],['peas',150,'g']],
    steps:['Cut potatoes into chips, toss in oil, bake at 200°C for 30 minutes.','Bake breaded fish for the last 15 minutes.','Boil peas.','Serve together.'] },
  { id:'r30', title:'Chicken Caesar Wrap', emoji:'🥙', tags:['quick','healthy'], appliances:['hob'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:false,dairyFree:false,nutFree:true,halal:true,kosher:true}, cookTime:12, cal:500, protein:36, carbs:40, fat:20, cost:3.70,
    ingredients:[['chicken breast',200,'g'],['tortilla',2,'pcs'],['lettuce',1,'bunch'],['parmesan',30,'g'],['caesar dressing',2,'tbsp']],
    steps:['Pan-fry and slice the chicken.','Toss lettuce with dressing and parmesan.','Fill tortillas with chicken and salad, roll.'] },
  { id:'r31', title:'Slow Cooker Chicken Curry', emoji:'🍛', tags:['asian','comfort','budget'], appliances:['slow_cooker'], diet:{vegan:false,vegetarian:false,pescatarian:false,glutenFree:true,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:240, cal:580, protein:38, carbs:52, fat:20, cost:3.90,
    ingredients:[['chicken thigh',300,'g'],['curry sauce',1,'can'],['onion',1,'pcs'],['rice',150,'g']],
    steps:['Add chicken, curry sauce and onion to the slow cooker.','Cook on low 6 hours.','Cook rice and serve.'] },
  { id:'r32', title:'Vegetable Stir Fry with Tofu', emoji:'🥦', tags:['vegan','quick','healthy'], appliances:['hob'], diet:{vegan:true,vegetarian:true,pescatarian:true,glutenFree:false,dairyFree:true,nutFree:true,halal:true,kosher:true}, cookTime:15, cal:460, protein:22, carbs:50, fat:16, cost:3.20,
    ingredients:[['tofu',200,'g'],['broccoli',150,'g'],['pepper',1,'pcs'],['soy sauce',2,'tbsp'],['rice',150,'g']],
    steps:['Pan-fry tofu cubes until golden, set aside.','Stir-fry broccoli and pepper 4-5 minutes.','Return tofu, add soy sauce, toss.','Serve over rice.'] }
];

// Per-base-unit price (GBP), keyed by keyword match against ingredient name.
// unit: 'g' priced per kg, 'ml' priced per litre, others priced flat per unit.
window.MEALS_PRICES = [
  { m:['salmon'], unit:'g', price:18.00 }, { m:['prawns'], unit:'g', price:16.00 },
  { m:['white fish'], unit:'g', price:11.00 }, { m:['steak'], unit:'g', price:14.00 },
  { m:['beef mince'], unit:'g', price:7.50 }, { m:['beef chunks','beef strips'], unit:'g', price:8.50 },
  { m:['chicken breast'], unit:'g', price:6.50 }, { m:['chicken thigh','cooked chicken','whole chicken'], unit:'g', price:5.00 },
  { m:['turkey mince'], unit:'g', price:6.00 }, { m:['pork shoulder'], unit:'g', price:6.00 },
  { m:['sausage'], unit:'pcs', price:0.45 }, { m:['halloumi'], unit:'g', price:9.00 },
  { m:['tofu'], unit:'g', price:3.50 }, { m:['feta'], unit:'g', price:8.00 },
  { m:['cheese','cheddar'], unit:'g', price:7.50 }, { m:['mozzarella'], unit:'g', price:6.50 },
  { m:['parmesan'], unit:'g', price:14.00 }, { m:['rice','arborio'], unit:'g', price:1.60 },
  { m:['pasta','spaghetti'], unit:'g', price:1.40 }, { m:['noodles'], unit:'g', price:1.80 },
  { m:['quinoa'], unit:'g', price:5.50 }, { m:['potato'], unit:'g', price:1.00 },
  { m:['sweet potato'], unit:'g', price:1.80 }, { m:['onion'], unit:'g', price:1.10 },
  { m:['garlic'], unit:'g', price:6.00 }, { m:['tomato'], unit:'g', price:2.20 },
  { m:['pepper'], unit:'pcs', price:0.55 }, { m:['broccoli'], unit:'g', price:2.00 },
  { m:['carrot'], unit:'g', price:1.00 }, { m:['spinach'], unit:'g', price:4.00 },
  { m:['cucumber'], unit:'pcs', price:0.65 }, { m:['lettuce','mixed leaves'], unit:'g', price:3.00 },
  { m:['cabbage'], unit:'g', price:1.00 }, { m:['mushroom'], unit:'g', price:4.50 },
  { m:['sweetcorn','black beans','kidney beans','chickpeas','baked beans','coconut milk','bbq sauce','curry sauce'], unit:'can', price:0.70 },
  { m:['lentils'], unit:'g', price:2.20 }, { m:['soy sauce'], unit:'tbsp', price:0.18 },
  { m:['olive oil'], unit:'tbsp', price:0.25 }, { m:['cream'], unit:'ml', price:2.20 },
  { m:['egg'], unit:'pcs', price:0.28 }, { m:['butter'], unit:'g', price:4.50 },
  { m:['bun'], unit:'pcs', price:0.40 }, { m:['tortilla'], unit:'pcs', price:0.30 },
  { m:['pizza dough'], unit:'pcs', price:1.20 }, { m:['lemon','lime'], unit:'pcs', price:0.38 },
  { m:['ginger'], unit:'g', price:6.00 }, { m:['chilli'], unit:'pcs', price:0.30 },
  { m:['curry paste'], unit:'tbsp', price:0.45 }, { m:['coleslaw'], unit:'pcs', price:1.50 },
  { m:['tahini'], unit:'g', price:9.00 }, { m:['peas','green beans'], unit:'g', price:1.50 },
  { m:['olives'], unit:'g', price:6.00 }, { m:['spring onion'], unit:'bunch', price:0.65 },
  { m:['basil','thyme'], unit:'bunch', price:1.00 }, { m:['salsa'], unit:'tbsp', price:0.20 },
  { m:['caesar dressing'], unit:'tbsp', price:0.30 }, { m:['chimichurri'], unit:'tbsp', price:0.35 },
  { m:['stock'], unit:'ml', price:0.50 }
];

// keyword -> supermarket aisle, used to group the shopping list.
window.MEALS_AISLES = [
  { m:['onion','garlic','pepper','tomato','broccoli','carrot','spinach','cucumber','lettuce','mixed leaves','cabbage','mushroom','potato','sweet potato','lemon','lime','ginger','chilli','spring onion','basil','thyme','green beans'], aisle:'Produce' },
  { m:['chicken','beef','turkey','pork','sausage','steak'], aisle:'Meat' },
  { m:['salmon','prawns','white fish'], aisle:'Fish' },
  { m:['cheese','cheddar','mozzarella','parmesan','feta','halloumi','cream','butter','egg','milk'], aisle:'Dairy' },
  { m:['peas','sweetcorn'], aisle:'Frozen' },
  { m:['rice','arborio','pasta','spaghetti','noodles','quinoa','lentils','black beans','kidney beans','chickpeas','baked beans','coconut milk','stock','tortilla','bun','pizza dough','tofu','tahini'], aisle:'Pantry' },
  { m:['soy sauce','olive oil','curry paste','curry sauce','bbq sauce','salsa','caesar dressing','chimichurri','olives'], aisle:'Sauces & Condiments' }
];

// expensive ingredient -> cheaper swap suggestion
window.MEALS_SUBSTITUTES = {
  'salmon':'tinned tuna or basa fillets', 'steak':'chicken thigh or pork loin',
  'prawns':'frozen white fish', 'halloumi':'extra-firm tofu',
  'parmesan':'a cheaper hard cheese', 'beef mince':'turkey mince',
  'pork shoulder':'chicken thighs in the slow cooker', 'white fish':'frozen basa or pollock'
};

// per-supermarket relative price multiplier
window.MEALS_SUPERMARKETS = {
  aldi:{ label:"Aldi", mult:0.85 }, lidl:{ label:"Lidl", mult:0.85 },
  tesco:{ label:"Tesco", mult:1.00 }, asda:{ label:"Asda", mult:0.95 },
  sainsburys:{ label:"Sainsbury's", mult:1.10 },
  rewe:{ label:"REWE", mult:1.05 }, netto:{ label:"Netto", mult:0.85 }
};
